import messengerImg from "../assets/apps-img/messenger.png";
import fitnessImg from "../assets/apps-img/fitness.png";
import musicImg from "../assets/apps-img/music.png";
import photoImg from "../assets/apps-img/photo.png";
import weatherImg from "../assets/apps-img/weather.png";
import foodImg from "../assets/apps-img/food.png";
import financeImg from "../assets/apps-img/finance.png";
import travelImg from "../assets/apps-img/travel.png";
import gamingImg from "../assets/apps-img/gaming.png";
import notesImg from "../assets/apps-img/notes.png";
import videoImg from "../assets/apps-img/video.png";
import shoppingImg from "../assets/apps-img/shopping.png";
import mapsImg from "../assets/apps-img/maps.png";
import cloudImg from "../assets/apps-img/cloud.png";
import calendarImg from "../assets/apps-img/calendar.png";
import educationImg from "../assets/apps-img/education.png";


export const appsData = [
  {
    id: 1,
    image: messengerImg,
    title: "ChatBuzz",
    companyName: "BuzzTech Inc.",
    description: "ChatBuzz is the ultimate messaging app that keeps you connected with friends, family, and colleagues. Enjoy instant messaging, voice calls, video chats, and group conversations all in one place. Share photos, videos, and documents seamlessly. With end-to-end encryption, your conversations stay private and secure.",
    size: 85,
    reviews: 24500,
    ratingAvg: 4.5,
    downloads: 5200000,
    ratings: [
      { name: "1 star", count: 320 },
      { name: "2 star", count: 580 },
      { name: "3 star", count: 2100 },
      { name: "4 star", count: 8500 },
      { name: "5 star", count: 13000 },
    ],
  },
  {
    id: 2,
    image: fitnessImg,
    title: "FitLife",
    companyName: "HealthLabs",
    description: "FitLife is your personal fitness coach. Track workouts, set goals, monitor your progress, and stay motivated with challenges and rewards. Includes meal plans, nutrition guides, and personalized workout routines for all levels.",
    size: 120,
    reviews: 19800,
    ratingAvg: 4.7,
    downloads: 4100000,
    ratings: [
      { name: "1 star", count: 150 },
      { name: "2 star", count: 300 },
      { name: "3 star", count: 900 },
      { name: "4 star", count: 5600 },
      { name: "5 star", count: 13000 },
    ],
  },
  {
    id: 3,
    image: musicImg,
    title: "TuneWave",
    companyName: "Soundly",
    description: "TuneWave lets you stream millions of songs anytime, anywhere. Create playlists, discover trending tracks, and enjoy high-quality audio. Follow your favorite artists and never miss a beat.",
    size: 95,
    reviews: 22300,
    ratingAvg: 4.6,
    downloads: 4800000,
    ratings: [
      { name: "1 star", count: 200 },
      { name: "2 star", count: 450 },
      { name: "3 star", count: 1500 },
      { name: "4 star", count: 8000 },
      { name: "5 star", count: 12000 },
    ],
  },
  {
    id: 4,
    image: photoImg,
    title: "SnapIt",
    companyName: "PixelWorks",
    description: "SnapIt is the perfect app for photography enthusiasts. Capture, edit, and share stunning photos with professional tools. Apply filters, enhance colors, and manage albums with ease.",
    size: 110,
    reviews: 17200,
    ratingAvg: 4.4,
    downloads: 3600000,
    ratings: [
      { name: "1 star", count: 180 },
      { name: "2 star", count: 400 },
      { name: "3 star", count: 1200 },
      { name: "4 star", count: 6200 },
      { name: "5 star", count: 9500 },
    ],
  },
  {
    id: 5,
    image: weatherImg,
    title: "WeatherNow",
    companyName: "SkyTech",
    description: "Get real-time weather updates, forecasts, and severe weather alerts with WeatherNow. Track temperature, humidity, wind speed, and more with interactive maps and widgets.",
    size: 70,
    reviews: 15000,
    ratingAvg: 4.3,
    downloads: 2800000,
    ratings: [
      { name: "1 star", count: 100 },
      { name: "2 star", count: 250 },
      { name: "3 star", count: 900 },
      { name: "4 star", count: 5400 },
      { name: "5 star", count: 9100 },
    ],
  },
  {
    id: 6,
    image: foodImg,
    title: "Foodies",
    companyName: "YumHub",
    description: "Foodies brings delicious recipes and meal inspirations to your fingertips. Browse recipes, create meal plans, and share your favorite dishes with the community.",
    size: 85,
    reviews: 13400,
    ratingAvg: 4.5,
    downloads: 3100000,
    ratings: [
      { name: "1 star", count: 120 },
      { name: "2 star", count: 300 },
      { name: "3 star", count: 1000 },
      { name: "4 star", count: 5200 },
      { name: "5 star", count: 8800 },
    ],
  },
  {
    id: 7,
    image: financeImg,
    title: "MoneyMind",
    companyName: "FinTech Solutions",
    description: "Manage your finances with MoneyMind. Track expenses, set budgets, monitor investments, and get insights to grow your wealth safely and efficiently.",
    size: 130,
    reviews: 18900,
    ratingAvg: 4.6,
    downloads: 3900000,
    ratings: [
      { name: "1 star", count: 210 },
      { name: "2 star", count: 400 },
      { name: "3 star", count: 1400 },
      { name: "4 star", count: 7200 },
      { name: "5 star", count: 9800 },
    ],
  },
  {
    id: 8,
    image: travelImg,
    title: "GlobeTrotter",
    companyName: "TravelWise",
    description: "Plan your next adventure with GlobeTrotter. Find destinations, book hotels, explore attractions, and manage itineraries all in one seamless travel app.",
    size: 150,
    reviews: 21200,
    ratingAvg: 4.7,
    downloads: 4500000,
    ratings: [
      { name: "1 star", count: 190 },
      { name: "2 star", count: 350 },
      { name: "3 star", count: 1100 },
      { name: "4 star", count: 8400 },
      { name: "5 star", count: 12200 },
    ],
  },
  {
    id: 9,
    image: gamingImg,
    title: "GameOn",
    companyName: "PlayZone",
    description: "GameOn brings you the best mobile games and e-sports tournaments. Connect with friends, compete in challenges, and enjoy exclusive rewards.",
    size: 180,
    reviews: 25800,
    ratingAvg: 4.8,
    downloads: 5700000,
    ratings: [
      { name: "1 star", count: 250 },
      { name: "2 star", count: 450 },
      { name: "3 star", count: 1600 },
      { name: "4 star", count: 9000 },
      { name: "5 star", count: 14000 },
    ],
  },
  {
    id: 10,
    image: notesImg,
    title: "QuickNotes",
    companyName: "NoteTech",
    description: "QuickNotes lets you jot down ideas, create checklists, and organize your notes with ease. Sync across devices and stay productive wherever you are.",
    size: 60,
    reviews: 14500,
    ratingAvg: 4.5,
    downloads: 3000000,
    ratings: [
      { name: "1 star", count: 130 },
      { name: "2 star", count: 290 },
      { name: "3 star", count: 950 },
      { name: "4 star", count: 5800 },
      { name: "5 star", count: 8330 },
    ],
  },
  {
    id: 11,
    image: videoImg,
    title: "StreamIt",
    companyName: "MediaFlow",
    description: "StreamIt allows you to watch your favorite movies, TV shows, and live events in high quality. Download for offline viewing and enjoy personalized recommendations.",
    size: 200,
    reviews: 27000,
    ratingAvg: 4.7,
    downloads: 6100000,
    ratings: [
      { name: "1 star", count: 240 },
      { name: "2 star", count: 500 },
      { name: "3 star", count: 1700 },
      { name: "4 star", count: 9200 },
      { name: "5 star", count: 14400 },
    ],
  },
  {
    id: 12,
    image: shoppingImg,
    title: "ShopEase",
    companyName: "RetailTech",
    description: "ShopEase is your ultimate shopping companion. Browse products, compare prices, track orders, and enjoy seamless checkout experiences.",
    size: 110,
    reviews: 19800,
    ratingAvg: 4.6,
    downloads: 4200000,
    ratings: [
      { name: "1 star", count: 180 },
      { name: "2 star", count: 400 },
      { name: "3 star", count: 1300 },
      { name: "4 star", count: 6800 },
      { name: "5 star", count: 10800 },
    ],
  },
  {
    id: 13,
    image: mapsImg,
    title: "MapQuest",
    companyName: "GeoWorks",
    description: "MapQuest offers accurate navigation, live traffic updates, and route planning. Explore new places with detailed maps and turn-by-turn directions.",
    size: 140,
    reviews: 22000,
    ratingAvg: 4.7,
    downloads: 4700000,
    ratings: [
      { name: "1 star", count: 200 },
      { name: "2 star", count: 370 },
      { name: "3 star", count: 1200 },
      { name: "4 star", count: 8200 },
      { name: "5 star", count: 12700 },
    ],
  },
  {
    id: 14,
    image: cloudImg,
    title: "CloudSafe",
    companyName: "DataSecure",
    description: "CloudSafe keeps your files safe in the cloud. Sync, backup, and access your documents from anywhere with secure cloud storage solutions.",
    size: 160,
    reviews: 17500,
    ratingAvg: 4.5,
    downloads: 3800000,
    ratings: [
      { name: "1 star", count: 140 },
      { name: "2 star", count: 310 },
      { name: "3 star", count: 1100 },
      { name: "4 star", count: 6000 },
      { name: "5 star", count: 8640 },
    ],
  },
  {
    id: 15,
    image: calendarImg,
    title: "PlannerPro",
    companyName: "TimeTech",
    description: "PlannerPro helps you manage your schedule, set reminders, and organize events efficiently. Sync across all your devices and never miss an important date.",
    size: 90,
    reviews: 13200,
    ratingAvg: 4.4,
    downloads: 2900000,
    ratings: [
      { name: "1 star", count: 120 },
      { name: "2 star", count: 280 },
      { name: "3 star", count: 950 },
      { name: "4 star", count: 5000 },
      { name: "5 star", count: 7850 },
    ],
  },
  {
    id: 16,
    image: educationImg,
    title: "EduLearn",
    companyName: "SmartEdu",
    description: "EduLearn brings educational content to your fingertips. Take courses, watch tutorials, and track your learning progress in a fun and interactive way.",
    size: 125,
    reviews: 21500,
    ratingAvg: 4.7,
    downloads: 4600000,
    ratings: [
      { name: "1 star", count: 180 },
      { name: "2 star", count: 350 },
      { name: "3 star", count: 1100 },
      { name: "4 star", count: 8400 },
      { name: "5 star", count: 12200 },
    ],
  },
];
